# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.1.1
_src_path: gh:algorandfoundation/algokit-react-frontend-template
author_email: vaibhavspatre@gmail.com
author_name: maroti
cloud_provider: none
preset_name: production
project_name: OnChain-Counter-frontend

