# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 2.1.4
_src_path: gh:algorandfoundation/algokit-fullstack-template
author_email: vaibhavspatre@gmail.com
author_name: maroti
cloud_provider: none
contract_name: counter
deployment_language: python
preset_name: production
project_name: OnChain-Counter

